apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: app-04
  namespace: flux-system
spec:
  releaseName: app-04
  targetNamespace: default
  storageNamespace: default
  chart:
    spec:
      chart: basic-app
      sourceRef:
        kind: HelmRepository
        name: getup
      version: 0.0.2
  dependsOn: []
  install:
    createNamespace: true
    disableWait: true
    remediation:
      retries: -1
  interval: 1m
  values:
    replicaCount: 2
    image:
      repository: nginx:alpine
      pullPolicy: IfNotPresent
